{extends file='pagina.tpl'} {block name='pagina'}
<div class='title'>Regulamento do Cartão de Pontos</div>
<div class='texto'>
    A Money One - Agência de Câmbios Lda é a impulsionadora do Cartão de Pontos MoneyOne que visa recompensar os seus clientes pela sua fidelidade e que se traduz na obtenção de pontos que poderão ser trocados por produtos ou serviços.
    <p>O Cartão de Pontos MoneyOne permite o acesso a prémios, produtos e serviços, quer nos balcões da MoneyOne - Agência de Câmbios Lda, quer junto de parceiros comerciais, que se associem ou constem da lista de parceiros comerciais. A iniciativa destina-se a todos os clientes MoneyOne - Agência de Câmbios Lda, sociedades ou particulares, que obtenham o Cartão de Pontos Money One.</p>
    <p>O Cartão de Pontos MoneyOne poderá ser obtido gratuitamente em qualquer balcão da MoneyOne, Lda. A promoção Cartão de Pontos MoneyOne é válida nos balcões da MoneyOne, Lda e nos estabelecimentos comerciais dos Parceiros Comerciais aderentes, melhor identificados no Catálogo da promoção. Poderão ainda aderir e beneficiar das condições do Cartão de Pontos MoneyOne, no âmbito das suas aquisições pessoais, os empregados da Money One - Agência de Câmbios Lda, de empresas suas associadas e dos revendedores, concessionários, agentes e fornecedores de serviços.</p>
    A utilização do Cartão de Pontos MoneyOne determina a aceitação das condições de utilização. A MoneyOne - Agência de Câmbios Lda publicará no site
    <a href="http://www.moneyexpress.pt/"  target="_blank">www.moneyexpress.pt</a>
    e no seu catálogo de pontos os prémios, produtos e serviços em vigor. A aquisição de bens e serviços de bens através do Cartão de Pontos MoneyOne está sujeita a disponibilidade de stocks, podendo ser substituídos por outros bens e serviços.
    <p>A Money One - Agência de Câmbios Lda poderá por iniciativa sua ou por facto imputável ao parceiro ou parceiros comerciais alterar a lista dos parceiros comerciais associados. As condições de aquisição e a garantia dos bens e serviços comercializados pelos parceiros comerciais são da sua inteira responsabilidade. A MoneyOne - Agência de Câmbios Lda poderá alterar as condições de acesso e de obtenção de bens e serviços através do Cartão de Pontos MoneyOne, sempre que tal se justifique, devendo para o efeito salvaguardar os interesses dos aderentes e publicitar as referidas alterações através do site www.moneyexpress.pt.</p>
</div>
<div class='subtitle'>Validade / Características</div>
<div class='texto'>
    <p>A MoneyOne - Agência de Câmbios Lda poderá cancelar, alterar ou substituir os termos da iniciativa o que deverá ser precedido de uma comunicação publicada no site <a href="http://www.moneyexpress.pt/"  target="_blank">www.moneyexpress.pt</a> com a antecedência mínima de 15 dias.</p>
</div>
<div class='subtitle'>Adesão</div>
<div class='texto'>
	Para participar nesta iniciativa será necessário ser possuidor do Cartão de Pontos MoneyOne, o qual poderá ser obtido gratuitamente em qualquer balcão da MoneyOne, Lda ou através da linha 800 207 214 / 211 452 500, mediante o preenchimento da respectiva proposta de adesão.
    <p>Após a adesão ao Cartão de Pontos MoneyOne os titulares recebem um cartão personalizado e passam a fazer parte desta iniciativa.</p>
    <p>A MoneyOne - Agência de Câmbios Lda obriga-se, nos termos da lei, a utilizar os dados processados e armazenados informaticamente na análise, decisão e gestão dos serviços a prestar e na utilização dos endereços para envio de informações no âmbito da iniciativa.</p>
    <p>Os portadores de cartões MoneyOne devem comunicar a Money One, Lda qualquer alteração relevante dos dados registados através do boletim de adesão, que poderão ser consultados pelo titular nos respectivos balcões.</p>
    <p>A adesão e a iniciativa Cartão de Pontos MoneyOne cessa com a entrega do cartão, por decisão da MoneyOne – Agência de Câmbios, Lda, comunicada ao titular do cartão com a antecedência mínima de 60 dias.</p>
</div>
<div class='subtitle'>Cartão de Pontos MoneyOne</div>
<div class='texto'>
    <p>A iniciativa é titulada por um cartão individualizado designado “MoneyOne” que incorpora pontos resultantes da aquisição de serviços prestados e/ou de iniciativas promocionais da MoneyOne, Lda.</p>
    <p>Para segurança do titular o Cartão de Pontos MoneyOne terá um prazo de validade, que não excederá os 4 anos. Os pontos acumulados no Cartão de Pontos MoneyOne permitem ao titular obter bens, serviços e vantagens comerciais junto da MoneyOne, Lda e dos parceiros comerciais associados à iniciativa. As vantagens, produtos e serviços oferecidos ao utilizador do Cartão de Pontos MoneyOne pode variar de acordo com critérios regionais, demográficos ou do tipo de Cliente alvo.</p>
    <p>O Cartão de Pontos MoneyOne é pessoal e intransmissível, devendo o titular identificar-se sempre que tal lhe for solicitado pela MoneyOne - Agência de Câmbios Lda ou pelos parceiros comerciais associados.</p>
    <p>O utilizador do Cartão de Pontos MoneyOne deve fazer uma utilização adequada do cartão por forma a que este se mantenha em boas condições. A Money One - Agência de Câmbios Lda e os parceiros associados à iniciativa Cartão de Pontos MoneyOne podem recusar-se a aceitar cartões onde seja detectada fraude, utilização indevida ou que não estejam dentro dos limites de identificação técnica impostos pelo sistema.</p>
    <p>O Cartão de Pontos MoneyOne acumula até 100.000 pontos e quando atingir o seu limite o titular do cartão deverá rebater os pontos por bens, serviços ou benefícios juntos dos balcões da MoneyOne ou dos parceiros comerciais associados.</p>
    <p>A utilização do Cartão de Pontos MoneyOne supõe o conhecimento e aceitação dos regulamentos da iniciativa e das suas condições gerais. A MoneyOne - Agência de Câmbios Lda não se responsabiliza pela perda ou furto do Cartão de Pontos MoneyOne, pelo que a emissão de um novo cartão não implica a creditação dos pontos acumulados.</p>
    <p>A MoneyOne - Agência de Câmbios Lda não está obrigada a fornecer novos cartões quando seja evidente que o utilizador fez um uso indevido do mesmo, nomeadamente quando exista fraude ou tentativa de adulteração dos dados físicos ou digitais incorporados no Cartão de Pontos Cartão de Pontos.</p>
    <p>O titular do Cartão de Pontos deverá dirigir-se aos balcões da MoneyOne - Agência de Câmbios Lda para trocar o cartão quando este atingir a sua data limite ou requerer o envio de um novo cartão através do site www.moneyexpress.pt.</p>
    <p>Sempre que o novo cartão seja enviado para o domicilio, o titular do Cartão de Pontos MoneyOne deverá deslocar-se aos balcões da MoneyOne - Agência de Câmbios Lda para que lhe sejam creditados os pontos, devendo para o efeito, restituir o cartão antigo.</p>
</div>
<div class='subtitle'>Pontos MoneyOne</div>
<div class='texto'>
    <p>Os pontos MoneyOne são emitidos pelos balcões da rede MoneyOne - Agência de Câmbios Lda e por parceiros comerciais devidamente autorizados.</p>
    <p>Os pontos atribuídos pela MoneyOne - Agência de Câmbios Lda, no âmbito desta iniciativa poderão ter um prazo limite de utilização e nesse caso serão anulados todos os pontos não rebatidos dentro do período máximo de utilização.</p>
    <p>Se a MoneyOne - Agência de Câmbios Lda optar por limitar a utilização dos pontos, obriga-se a fazer constar esse facto do catálogo e a possibilitar ao titular do Cartão de Pontos MoneyOne a consulta do saldo de pontos através de um extracto actualizado em cada remessa.</p>
    <p>Sempre que não for possível creditar os pontos no Cartão de Pontos MoneyOne o titular do cartão deverá dirigir-se a um dos balcões da rede MoneyOne - Agência de Câmbios Lda e solicitar que os mesmos lhe sejam creditados, o que deverá acontecer no prazo máximo de 30 (trinta) dias.</p>
    <p>O titular também poderá consultar o saldo do seu Cartão de Pontos MoneyOne em qualquer dos balcões da rede MoneyOne - Agência de Câmbios Lda. Os pontos MoneyOne não são convertíveis em dinheiro e o Cartão de Pontos MoneyOne não é um cartão de débito ou crédito. Os pontos MoneyOne não podem ser transaccionados.</p>		
</div>
<div class='subtitle'>Atribuição dos pontos MoneyOne</div>
<div class='texto'>
    <p>Os pontos MoneyOne são concedidos, com base nas indicações fornecidas pelo catálogo vigente, através de: 1) Campanhas promocionais com atribuição individual de pontos; 2) Remessas ou troca de moedas efetuadas nos balcões da rede MoneyOne - Agência de Câmbios Lda aderentes, bem como aquisição de produtos ou serviços junto de outras entidades parceiras; 3) Sistema de recompensa pela frequência/intensidade de compras;</p>
    <p>Em acções promocionais específicas os pontos MoneyOne poderão ser conferidos, por um período de tempo determinado, em quantidades diferentes das estipuladas, a atribuição de bónus sujeitos a critérios devidamente limitados e individualizados ou a inibição da concessão de pontos quando exista proveito na aquisição de ofertas no âmbito do programa Cartão de Pontos MoneyOne.</p>
	As promoções e sistema de recompensa mencionadas no catálogo poderão ser canceladas em qualquer momento. A forma de pagamento executada por remessa nas agências poderão condicionar o crédito dos pontos.
    <p>A obtenção de benefícios referentes a programas promovidos pela MoneyOne - Agência de Câmbios Lda. ou nos quais a MoneyOne - Agência de Câmbios, Lda. se associe poderá originar a exclusão de atribuição de pontos por meio de comunicação expressa ao cliente no âmbito do programa ou acção sobre o qual incide a exclusão.</p>
    <p>A concessão de pontos do programa cartão pontos MoneyOne poderá levar à eliminação da aquisição de vantagens relacionados com outros programas fomentados pela MoneyOne - Agência de Câmbios Lda. ou nos quais a MoneyOne - Agência de Câmbios Lda. se associe, por meio de comunicação expressa ao cliente no âmbito do programa ou acção sobre o qual incide a exclusão.</p>
    <p>Não haverá concessão de pontos nas seguintes situações:</p>
	1) Remessas ou troca de moedas efetuadas nos balcões da rede MoneyOne - Agência de Câmbios Lda não aderentes ao programa Cartão de Pontos MoneyOne; 2) Compras de produtos e serviços de parceiros não aderentes ao programa Cartão de Pontos MoneyOne;
</div>
<div class='subtitle'>Vale Manual de Pontos</div>
<div class='texto'>
    <p>Quando o terminal electrónico se encontrar avariado ou quando não reconhece o cartão eventualmente danificado, a MoneyOne - Agência de Câmbios Lda. poderá lançar, relativamente à remessa efetuada, um Vale Manual de Pontos. Atendendo aos limites diários fixados pelo sistema, os pontos concedidos através de Vale Manual de Pontos podem ser consignados no Cartão de Pontos MoneyOne. Os vales ilegíveis, ou adquiridos por meio fraudulento, roubo, ou por qualquer outro meio que não nas condições acima fixadas, não serão admitidos pela MoneyOne - Agência de Câmbios</p>
</div>
<div class='subtitle'>Donativos</div>
<div class='texto'>
    <p>A MoneyOne - Agência de Câmbios Lda. poderá atribuir donativos a instituições particulares ou públicas de solidariedade social. Os indicadores de actividade do programa, num período de tempo delimitado, serão determinantes para a quantificação dos donativos. Os critérios para estas acções estarão contidos em regulamentos que serão transmitidos de forma expressa em momento anterior à sua execução. Os recibos de todos os donativos serão passados à MoneyOne - Agência de Câmbios Lda. na qualidade de entidade pagadora. Rebate de pontos MoneyOne – Entrega de prémios. Os catálogos vigentes, folhetos ou outro tipo de meio de divulgação emitidos pela MoneyOne, disciplinarão os critérios de rebate de pontos. Os pontos disponíveis no cartão serão rebatidos por cada vez que se opere um resgate de prémios, regalias, benefícios e outros produtos ou serviços em vigor. Os empregados da MoneyOne - Agência de Câmbios Lda., empresas associadas da MoneyOne - Agência de Câmbios Lda,
	revendedores, concessionários, distribuidores, agentes, prestadores de serviços, bem como os respectivos empregados e familiares, só podem reclamar prémios ou descontos, utilizando pontos adquiridos através das suas compras pessoais. Os prémios são limitados aos stocks existentes. A MoneyOne - Agência de Câmbios Lda reserva-se o direito de substituir os prémios por ofertas idênticas ou de valor semelhante.</p>
</div>
<div class='subtitle'>Devoluções</div>
<div class='texto'>
    <p>As devoluções podem ser realizadas até um prazo máximo de 30 dias a contar da data de recepção do prémio. As devoluções estão sujeitas aos critérios que se seguem: 1) Os prémios devem ser restituídos, sem qualquer uso, na sua embalagem original, com os respectivos manuais e acessórios; 2) O talão de rebate original ou qualquer outro comprovativo de entrega deve ser igualmente apresentado; 3) Deverá ser indicado o prémio, o motivo da devolução e a intenção da substituição do prémio por outro equivalente ou a sua reposição por pontos; Caso não sejam respeitadas as condições acima referidas a devolução não será aceite. Os custos do envio do prémio devolvido ficam a cargo do cliente, não sendo aceites as encomendas enviadas à cobrança. A MoneyOne - Agência de Câmbios Lda reserva-se até 30 dias para realizar, por crédito em pontos na conta corrente dos pontos do cliente, o eventual reembolso, que apenas dirá respeito aos pontos do artigo devolvido. A devolução pode ser efetuada num balcão aderente da rede MoneyOne - Agência de Câmbios Lda. Após uma avaliação criteriosa do estado do prémio, a MoneyOne - Agência de Câmbios Lda., agirá conforme a preferência demonstrada pelo cliente e, no que diz respeito a prémios devolvidos à cobrança em casa, ao eventual reembolso das despesas efetuadas. As condições de devolução enunciadas entram em vigor a partir do dia 01 de Novembro de 2008. As deficiências, verificadas após o prazo de devolução, deverão ser reclamadas junto dos fornecedores, apresentando a respectiva garantia. A informação acerca das garantias do fornecedor/fabricante pode ser obtida através da Linha 800 207 214 / 211 452 500 ou pelo correio para Programa Cartão de Pontos MoneyOne – Av. Duque de Loulé, nº 123, Galeria 2, 1069-152, Lisboa, Portugal.</p>
    <p>Os pontos MoneyOne pode ser trocados num balcão aderente da rede MoneyOne - Agência de Câmbios Lda. por: 
    <p>&nbsp;</p>
    <p>1) Prémios de catálogo de entrega imediata num balcão aderente da rede MoneyOne - Agência de Câmbios Lda., debitando-se os pontos acumulados no cartão. Se inexistir em stock no balcão um determinado artigo, o titular do Cartão de Pontos MoneyOne pode proceder à sua encomenda. Em consequência, a entrega do prémio seguirá os trâmites estabelecidos no ponto abaixo mencionado como “ 2- Prémio de catálogo de entrega diferida no balcão”. Para efeitos de garantia, o titular do Cartão de Pontos MoneyOne deverá assegurar-se de que recebe o talão de rebate ou qualquer outro comprovativo de entrega do prémio.</p>
    <p>&nbsp;</p>
    <p>2) Prémios de catálogo de entrega diferida no balcão: Os prémios de catálogo de entrega diferida no posto só podem ser obtidos por rebate de pontos no cartão, sendo que é apenas possível efetuar um rebate de cada vez. Os prémios devem ser levantados no balcão onde foram solicitados, cerca de 15 dias úteis depois do pedido, apresentando, para o efeito, o vale MoneyOne emitido no momento da requisição do prémio. Se esta troca não for efetuada, o cartão permanecerá num estado de “brinde pendente” que impede sejam feitos novos pedidos de prémios por Entrega Diferida no balcão. Os prémios conservar-se-ão no balcão até cinco semanas após o pedido, sendo que a MoneyOne - Agência de Câmbios Lda não se responsabiliza, após o término do prazo, pela a sua permanência no posto. Poderá ser exigido ao possuidor do vale MoneyOne a apresentação do seu cartão ou outro elemento comprovativo da sua identidade. Para efeitos de garantia, o titular do Cartão de Pontos MoneyOne deverá certificar-se de que recebe o comprovativo de entrega. Apenas serão considerados rebates efectuados por cartões aderentes ao programa Cartão de Pontos MoneyOne em Portugal.</p>
    <p>&nbsp;</p>
    <p>3) Prémios de catálogo de entrega diferida em casa: Os prémios podem ser adquiridos por rebate dos pontos acumulados no cartão, ou envolver, para além do rebate de pontos, uma comparticipação adicional em dinheiro. Os prémios, cujos custos de envio são suportados pelo cliente, serão enviados num período aproximado de 15 dias úteis após a recepção do pedido. Os valores dos produtos a comparticipar pelos aderentes ao programa Cartão de Pontos MoneyOne incluem IVA. Por forma a evitar demoras na entrega dos artigos solicitados, correcções e eventuais alterações de dados (nome, morada, telefone) deverão ser comunicadas através da Linha 800 207 214 / 211 452 500 ou por intermédio do endereço www.moneyexpress.pt na Internet, ou por correio para o Programa Cartão de Pontos MoneyOne – Av. Duque de Loulé, nº 123, Galeria 2, 1069-152, Lisboa, Portugal. Para efeitos de garantia, o titular do Cartão de Pontos MoneyOne deverá certificar-se de que recebe o talão de rebate de pontos. Apenas serão considerados rebates efectuados por cartões aderentes ao programa Cartão de Pontos MoneyOne em Portugal.</p>
    <p>&nbsp;</p>
    <p>4) Benefícios em parceiros: O catálogo vigente regulamenta a obtenção de vales MoneyOne / vales de rebate para acesso a regalias, benefícios e vantagens na aquisição de produtos e serviços aos parceiros do programa. A – Os pontos MoneyOne podem ser trocados junto dos parceiros da seguinte forma: O rebate de pontos acumulados no cartão nos terminais electrónicos / P.O.S., em caso de existência destes equipamentos nos balcões, ou a apresentação do vale Cartão de Pontos MoneyOne, obtido anteriormente nos balcões MoneyOne - Agência de Câmbios Lda. aderentes, permitirá a obtenção de regalias e vantagens na aquisição de produtos e serviços aos parceiros de programa. B – Condições particulares de utilização do cartão: A simples apresentação do Cartão de Pontos MoneyOne permitirá a obtenção de regalias e vantagens na aquisição de produtos e serviços. Os prémios, regalias, benefícios e outros produtos e serviços referentes às entidades terceiras participantes no programa são da sua exclusiva responsabilidade e poderão ser obtidos junto das mesmas em função das condições apresentadas no catálogo em vigor, folhetos ou outro tipo de informação que, para esse efeito, a MoneyOne - Agência de Câmbios Lda divulgue.</p>
    <p>&nbsp;</p>
</div>
{/block}